name: tinkering
channels:
  - conda-forge
dependencies:
  - pandas
  - geopandas
  - numpy
  - scipy
  - matplotlib
  - dask
  - datashader
  - pygeos
  - osmnx
  - pyrosm
  - networkx
  - clustergram
  - bokeh
  - scikit-learn
  - geopy
  - ipywidgets
  - contextily
  - cenpy
  - pip:
    - google-cloud-bigquery[pandas
    - igraph
    - leidenalg
