---
title: "SPATIAL ANALYSIS IN R"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
subtitle: "with applications for Grand Challenges"
author: "andrew renninger"
date: "8/23/2019"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE, cache = TRUE)
```

# [1] Network Analysis

## Principles

## Ideas

# [2] Streets as nodes

We can think about this philosophy of streets as the walking model—compared to, say, driving or briking. 

```{r data}

library(tigris)
library(sf)

roads <- roads("PA", "Philadelphia", class = 'sf')
tracts <- tracts("PA", "Philadelphia", class = 'sf')

water <- 
  area_water("PA", "Philadelphia", class = 'sf') %>%
  st_union() %>%
  st_combine()

projection <- st_crs(roads)

```

```{r tidyverse, eval = FALSE}

library(tidyverse)

```

```{r}

background <-
  tracts %>%
  mutate(dissolve = 1) %>%
  group_by(dissolve) %>%
  summarise() %>%
  st_difference(water)

```

```{r basemap} 

background <-
  tracts %>%
  mutate(dissolve = 1) %>%
  group_by(dissolve) %>%
  summarise() %>%
  st_difference(water)

```

```{r}

difference <- st_difference(roads)
intersection <- st_intersection(difference)

```

```{r}

nodes <-
  intersection %>%
  mutate(type = st_geometry_type(geometry)) %>%
  filter(type == "POINT") %>%
  select(-type) %>%
  st_as_sf()

```

## Community Detection

## 

# [3] Streets as edges

## 

## 

# [4] Thematic coding